version: '2'
services:
  dressup:
    build: .
    environment:
     - DISPLAY=$DISPLAY
     - QT_X11_NOMITSHM=1
    privileged: true
    volumes:
     - '/tmp/.X11-unix:/tmp/.X11-unix'
    devices:
     - /dev/video0
     - /dev/nvidia0

